@InvestmentExercise_HostAddress = http://localhost:5062

POST {{InvestmentExercise_HostAddress}}/api/Investment
Content-Type: application/json

{
  "oportunityId": 2,
  "userId": 2,
  "amount": 50
}
###

GET {{InvestmentExercise_HostAddress}}/api/Oportunity
Content-Type: application/json
###

PUT {{InvestmentExercise_HostAddress}}/api/User/balance
Content-Type: application/json

{
  "userId": 2,
  "amount": 9000,
  "action": "add"
}
###

